### PR TITLE
Feat/assume role role

### PR DESCRIPTION
**Pull request by kerbyferris**
# Description

Add ansible role allowing jobs user to assume role into other aws accounts

### CODE REVIEW

**Comment by kerbyferris** [comment]
recheck

**Comment by kerbyferris** [comment]
recheck

**Comment by kerbyferris** [comment]
recheck

**Comment by kerbyferris** [comment]
recheck

**Comment by SpamapS** [comment]
gate-recheck

**Comment by kerbyferris** [comment]
gate-recheck

**Comment by kerbyferris** [comment]
gate-recheck

**Comment by kerbyferris** [comment]
gate-recheck

**Pull request merged**
