### PR TITLE
remove roles related to docker build user

### PR DESCRIPTION
**Pull request by kerbyferris**
Clean up references and roles related to the docker build user, which is no longer required.

Depends-on: https://github.com/GoodMoney/tech/pull/843

### CODE REVIEW

**Comment by kerbyferris** [comment]
This will need to wait for GoodMoney/tech#843 before it can land safely.

**Comment by kerbyferris** [comment]
recheck

**Comment by kerbyferris** [comment]
recheck

**Comment by SpamapS** [comment]
Superseded by #30

**Pull request closed without merging**
